spring:
  application:
    name: expenses-tracker
  data:
    mongodb:
      uri: "mongodb://admin:admin123@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&authSource=admin&appName=mongosh+2.8.2"
      database: "expenses_tracker_db"
